variable "account_id" {}
variable "environment" {}
variable "project_name" {}
variable "aws_region" {}
variable "api_gateway" {}
variable "pathpart" {}
variable "req_model" {}
variable "infer_lambda" {}
variable "worker_lambda" {}
variable "cw_api_lg" {}
variable "usage_plan_name" {}
variable "burst_limit" {}
variable "rate_limit" {}        
variable "quota_limit" {}
variable "quota_period" {}   
variable "apikey_name" {}
variable "br_gr_name" {}
variable "sec_trails_name" {}
variable "cw_secret_lg" {}
variable "cw_lg_role" {}
variable "cw_lg_apigw" {}
variable "cw_lg_welcome" {}
variable "cw_lg_bedrock" {}
variable "cw_lg_infer" {}
variable "cw_lg_worker" {}
variable "cw_lg_secretstrail" {}
variable "cw_lg_waf" {} 
variable "iam_api_cw_role" {}
variable "iam_lambda_role" {}
variable "waf_metric_name" {}
variable "waf_limit" {}
variable "waf_agg_type" {}
variable "waf_eval_window" {}
variable "waf_webacl_name" {}
variable "sm_br_api_key" {}
variable "gw_invoke_id" {}
variable "api_id" {}
variable "kms_master_key_id" {}
variable "scanora_bucket_name" {}
variable "lambda_infer_role" {}
variable "lambda_invoke" {}
variable "sm_br_policy" {}
variable "lambda_exec_role" {}
variable "lambda_infer_api" {}
variable "lambda_infer_s3" {}
variable "cw_br_role" {}
variable "cw_br_pol" {}
variable "cw_st_role" {}
variable "cw_st_pol" {}
variable "cw_ls_bedrock" {}
variable "sm_secret" {}
variable "s3_json_folder" {}
variable "s3_resp_folder" {}
variable "s3_presigned_expiry" {}
variable "br_model" {}
variable "ct_bucket_name" {}
